[device.syr3]  # transfer; solvent
address = 3
type = "Elite11"
port = "COM5"
syringe_diameter = "4.608 mm"
syringe_volume = "1 ml"
force = 90

[device.6PortValve]
type = "KnauerValve"
mac_address = "00:80:a3:b4:ce:80"
network = "141.14.*.*"

[device.syr5]  # high concentration mixture; quencher
address = 5
type = "Elite11"
port = "COM5"
syringe_diameter = "14.567 mm"
syringe_volume = "10 ml"

[device.r2]
type = "R2"
port = "COM6"

[device.O2MFC]
type = "MFC"
port = "COM7"
address = 6
max_flow = 10
#gas = "oxygen"

[device.pressMFC]
type = "MFC"
port = "COM7"
address = 1
max_flow = 10

[device.pressEPC]
type = "EPC"
port = "COM7"
address = 2
#max_pressure = 10

[device.HPLCvalve]
type = "KnauerValve"
mac_address = "00:80:a3:ce:7f:08"
network = "141.14.*.*"

[device.Knauer-pumpM]
type = "AzuraCompact"
mac_address = "00:80:a3:ba:ef:3b"
network = "192.168.10.*"

[device.bubble-sensor-power]
type = "PhidgetPowerSource5V"
vint_serial_number=627768
vint_hub_port =3
vint_channel=0

[device.bubble-sensor-measure]
type = "PhidgetBubbleSensor"
vint_serial_number=627768
vint_hub_port =0
vint_channel=0
data_interval=20

